name: ðŸš€ Deploy to Somee via FTP

on:
  push:
    branches:
      - main   # hoáº·c master náº¿u báº¡n dÃ¹ng nhÃ¡nh Ä‘Ã³

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files to Somee
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: testgithubaction.somee.com
          username: ${{ secrets.SOMEE_FTP_USER }}
          password: ${{ secrets.SOMEE_FTP_PASS }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /www.testgithubaction.somee.com/       # thÆ° má»¥c gá»‘c web Somee
          log-level: verbose
